In [28]:
import math
import itertools
import numpy as np
import plotly.express as px
import pandas as pd
import plotly.graph_objects as go


p = np.arange(0, 9, 1)

def fgx(x):
    return 0.5 * np.power(x,2) + 3 * x + 10

def apromixate(N):
    global fgx

    gaussian_noise = np.random.normal(0, 4, N)
    x = np.linspace(-15, 10, num=N)
    y = fgx(x)
    y_noise = y + gaussian_noise

    h = []
    for degree_of_the_polynomial in range(1, 9):
        h = np.vstack([x**degree for degree in range(0, degree_of_the_polynomial + 1) ]).T
        print(h)
        w = np.linalg.pinv(h).dot(y_noise)
        y_aproximate = h.dot(w)

        amostrage = px.scatter(x=x, y=y_noise, template="seaborn", color_discrete_sequence=['red'], title="p = {degree_of_the_polynomial}".format(degree_of_the_polynomial=degree_of_the_polynomial), width=800, height=700)
        
        amostrage.update_traces(hoverinfo='skip', marker=dict(size=8,line=dict(width=2,color='black')),selector=dict(mode='markers'))

        aproximation = go.Scatter(x=x, y=y_aproximate, mode='lines', line = dict(color='green'), name='Aproximation')

        real = go.Scatter(x=x, y=y, mode='lines', line = dict(color='royalblue', dash='dash'), name='Fg(x)')

        amostrage.add_trace(aproximation)
        
        amostrage.add_trace(real)
        
        amostrage.show()

        h = []



print('N = 10')
apromixate(10)




N = 10
[[  1.         -15.        ]
 [  1.         -12.22222222]
 [  1.          -9.44444444]
 [  1.          -6.66666667]
 [  1.          -3.88888889]
 [  1.          -1.11111111]
 [  1.           1.66666667]
 [  1.           4.44444444]
 [  1.           7.22222222]
 [  1.          10.        ]]


[[  1.         -15.         225.        ]
 [  1.         -12.22222222 149.38271605]
 [  1.          -9.44444444  89.19753086]
 [  1.          -6.66666667  44.44444444]
 [  1.          -3.88888889  15.12345679]
 [  1.          -1.11111111   1.2345679 ]
 [  1.           1.66666667   2.77777778]
 [  1.           4.44444444  19.75308642]
 [  1.           7.22222222  52.16049383]
 [  1.          10.         100.        ]]


[[ 1.00000000e+00 -1.50000000e+01  2.25000000e+02 -3.37500000e+03]
 [ 1.00000000e+00 -1.22222222e+01  1.49382716e+02 -1.82578875e+03]
 [ 1.00000000e+00 -9.44444444e+00  8.91975309e+01 -8.42421125e+02]
 [ 1.00000000e+00 -6.66666667e+00  4.44444444e+01 -2.96296296e+02]
 [ 1.00000000e+00 -3.88888889e+00  1.51234568e+01 -5.88134431e+01]
 [ 1.00000000e+00 -1.11111111e+00  1.23456790e+00 -1.37174211e+00]
 [ 1.00000000e+00  1.66666667e+00  2.77777778e+00  4.62962963e+00]
 [ 1.00000000e+00  4.44444444e+00  1.97530864e+01  8.77914952e+01]
 [ 1.00000000e+00  7.22222222e+00  5.21604938e+01  3.76714678e+02]
 [ 1.00000000e+00  1.00000000e+01  1.00000000e+02  1.00000000e+03]]


[[ 1.00000000e+00 -1.50000000e+01  2.25000000e+02 -3.37500000e+03
   5.06250000e+04]
 [ 1.00000000e+00 -1.22222222e+01  1.49382716e+02 -1.82578875e+03
   2.23151959e+04]
 [ 1.00000000e+00 -9.44444444e+00  8.91975309e+01 -8.42421125e+02
   7.95619951e+03]
 [ 1.00000000e+00 -6.66666667e+00  4.44444444e+01 -2.96296296e+02
   1.97530864e+03]
 [ 1.00000000e+00 -3.88888889e+00  1.51234568e+01 -5.88134431e+01
   2.28718945e+02]
 [ 1.00000000e+00 -1.11111111e+00  1.23456790e+00 -1.37174211e+00
   1.52415790e+00]
 [ 1.00000000e+00  1.66666667e+00  2.77777778e+00  4.62962963e+00
   7.71604938e+00]
 [ 1.00000000e+00  4.44444444e+00  1.97530864e+01  8.77914952e+01
   3.90184423e+02]
 [ 1.00000000e+00  7.22222222e+00  5.21604938e+01  3.76714678e+02
   2.72071712e+03]
 [ 1.00000000e+00  1.00000000e+01  1.00000000e+02  1.00000000e+03
   1.00000000e+04]]


[[ 1.00000000e+00 -1.50000000e+01  2.25000000e+02 -3.37500000e+03
   5.06250000e+04 -7.59375000e+05]
 [ 1.00000000e+00 -1.22222222e+01  1.49382716e+02 -1.82578875e+03
   2.23151959e+04 -2.72741283e+05]
 [ 1.00000000e+00 -9.44444444e+00  8.91975309e+01 -8.42421125e+02
   7.95619951e+03 -7.51418843e+04]
 [ 1.00000000e+00 -6.66666667e+00  4.44444444e+01 -2.96296296e+02
   1.97530864e+03 -1.31687243e+04]
 [ 1.00000000e+00 -3.88888889e+00  1.51234568e+01 -5.88134431e+01
   2.28718945e+02 -8.89462565e+02]
 [ 1.00000000e+00 -1.11111111e+00  1.23456790e+00 -1.37174211e+00
   1.52415790e+00 -1.69350878e+00]
 [ 1.00000000e+00  1.66666667e+00  2.77777778e+00  4.62962963e+00
   7.71604938e+00  1.28600823e+01]
 [ 1.00000000e+00  4.44444444e+00  1.97530864e+01  8.77914952e+01
   3.90184423e+02  1.73415299e+03]
 [ 1.00000000e+00  7.22222222e+00  5.21604938e+01  3.76714678e+02
   2.72071712e+03  1.96496236e+04]
 [ 1.00000000e+00  1.00000000e+01  1.00000000e+02  1.00000000e+03
   1.00000000e+04  1.0000

[[ 1.00000000e+00 -1.50000000e+01  2.25000000e+02 -3.37500000e+03
   5.06250000e+04 -7.59375000e+05  1.13906250e+07]
 [ 1.00000000e+00 -1.22222222e+01  1.49382716e+02 -1.82578875e+03
   2.23151959e+04 -2.72741283e+05  3.33350457e+06]
 [ 1.00000000e+00 -9.44444444e+00  8.91975309e+01 -8.42421125e+02
   7.95619951e+03 -7.51418843e+04  7.09673352e+05]
 [ 1.00000000e+00 -6.66666667e+00  4.44444444e+01 -2.96296296e+02
   1.97530864e+03 -1.31687243e+04  8.77914952e+04]
 [ 1.00000000e+00 -3.88888889e+00  1.51234568e+01 -5.88134431e+01
   2.28718945e+02 -8.89462565e+02  3.45902109e+03]
 [ 1.00000000e+00 -1.11111111e+00  1.23456790e+00 -1.37174211e+00
   1.52415790e+00 -1.69350878e+00  1.88167642e+00]
 [ 1.00000000e+00  1.66666667e+00  2.77777778e+00  4.62962963e+00
   7.71604938e+00  1.28600823e+01  2.14334705e+01]
 [ 1.00000000e+00  4.44444444e+00  1.97530864e+01  8.77914952e+01
   3.90184423e+02  1.73415299e+03  7.70734663e+03]
 [ 1.00000000e+00  7.22222222e+00  5.21604938e+01  3.76714678e+0

[[ 1.00000000e+00 -1.50000000e+01  2.25000000e+02 -3.37500000e+03
   5.06250000e+04 -7.59375000e+05  1.13906250e+07 -1.70859375e+08]
 [ 1.00000000e+00 -1.22222222e+01  1.49382716e+02 -1.82578875e+03
   2.23151959e+04 -2.72741283e+05  3.33350457e+06 -4.07428336e+07]
 [ 1.00000000e+00 -9.44444444e+00  8.91975309e+01 -8.42421125e+02
   7.95619951e+03 -7.51418843e+04  7.09673352e+05 -6.70247054e+06]
 [ 1.00000000e+00 -6.66666667e+00  4.44444444e+01 -2.96296296e+02
   1.97530864e+03 -1.31687243e+04  8.77914952e+04 -5.85276635e+05]
 [ 1.00000000e+00 -3.88888889e+00  1.51234568e+01 -5.88134431e+01
   2.28718945e+02 -8.89462565e+02  3.45902109e+03 -1.34517487e+04]
 [ 1.00000000e+00 -1.11111111e+00  1.23456790e+00 -1.37174211e+00
   1.52415790e+00 -1.69350878e+00  1.88167642e+00 -2.09075158e+00]
 [ 1.00000000e+00  1.66666667e+00  2.77777778e+00  4.62962963e+00
   7.71604938e+00  1.28600823e+01  2.14334705e+01  3.57224508e+01]
 [ 1.00000000e+00  4.44444444e+00  1.97530864e+01  8.77914952e+01
   

[[ 1.00000000e+00 -1.50000000e+01  2.25000000e+02 -3.37500000e+03
   5.06250000e+04 -7.59375000e+05  1.13906250e+07 -1.70859375e+08
   2.56289062e+09]
 [ 1.00000000e+00 -1.22222222e+01  1.49382716e+02 -1.82578875e+03
   2.23151959e+04 -2.72741283e+05  3.33350457e+06 -4.07428336e+07
   4.97967966e+08]
 [ 1.00000000e+00 -9.44444444e+00  8.91975309e+01 -8.42421125e+02
   7.95619951e+03 -7.51418843e+04  7.09673352e+05 -6.70247054e+06
   6.33011107e+07]
 [ 1.00000000e+00 -6.66666667e+00  4.44444444e+01 -2.96296296e+02
   1.97530864e+03 -1.31687243e+04  8.77914952e+04 -5.85276635e+05
   3.90184423e+06]
 [ 1.00000000e+00 -3.88888889e+00  1.51234568e+01 -5.88134431e+01
   2.28718945e+02 -8.89462565e+02  3.45902109e+03 -1.34517487e+04
   5.23123559e+04]
 [ 1.00000000e+00 -1.11111111e+00  1.23456790e+00 -1.37174211e+00
   1.52415790e+00 -1.69350878e+00  1.88167642e+00 -2.09075158e+00
   2.32305731e+00]
 [ 1.00000000e+00  1.66666667e+00  2.77777778e+00  4.62962963e+00
   7.71604938e+00  1.2860082

In [29]:
print('N = 100')
apromixate(100)

N = 100
[[  1.         -15.        ]
 [  1.         -14.74747475]
 [  1.         -14.49494949]
 [  1.         -14.24242424]
 [  1.         -13.98989899]
 [  1.         -13.73737374]
 [  1.         -13.48484848]
 [  1.         -13.23232323]
 [  1.         -12.97979798]
 [  1.         -12.72727273]
 [  1.         -12.47474747]
 [  1.         -12.22222222]
 [  1.         -11.96969697]
 [  1.         -11.71717172]
 [  1.         -11.46464646]
 [  1.         -11.21212121]
 [  1.         -10.95959596]
 [  1.         -10.70707071]
 [  1.         -10.45454545]
 [  1.         -10.2020202 ]
 [  1.          -9.94949495]
 [  1.          -9.6969697 ]
 [  1.          -9.44444444]
 [  1.          -9.19191919]
 [  1.          -8.93939394]
 [  1.          -8.68686869]
 [  1.          -8.43434343]
 [  1.          -8.18181818]
 [  1.          -7.92929293]
 [  1.          -7.67676768]
 [  1.          -7.42424242]
 [  1.          -7.17171717]
 [  1.          -6.91919192]
 [  1.          -6.66666667]
 [  1.

[[ 1.00000000e+00 -1.50000000e+01  2.25000000e+02]
 [ 1.00000000e+00 -1.47474747e+01  2.17488011e+02]
 [ 1.00000000e+00 -1.44949495e+01  2.10103561e+02]
 [ 1.00000000e+00 -1.42424242e+01  2.02846648e+02]
 [ 1.00000000e+00 -1.39898990e+01  1.95717274e+02]
 [ 1.00000000e+00 -1.37373737e+01  1.88715437e+02]
 [ 1.00000000e+00 -1.34848485e+01  1.81841139e+02]
 [ 1.00000000e+00 -1.32323232e+01  1.75094378e+02]
 [ 1.00000000e+00 -1.29797980e+01  1.68475156e+02]
 [ 1.00000000e+00 -1.27272727e+01  1.61983471e+02]
 [ 1.00000000e+00 -1.24747475e+01  1.55619325e+02]
 [ 1.00000000e+00 -1.22222222e+01  1.49382716e+02]
 [ 1.00000000e+00 -1.19696970e+01  1.43273646e+02]
 [ 1.00000000e+00 -1.17171717e+01  1.37292113e+02]
 [ 1.00000000e+00 -1.14646465e+01  1.31438119e+02]
 [ 1.00000000e+00 -1.12121212e+01  1.25711662e+02]
 [ 1.00000000e+00 -1.09595960e+01  1.20112744e+02]
 [ 1.00000000e+00 -1.07070707e+01  1.14641363e+02]
 [ 1.00000000e+00 -1.04545455e+01  1.09297521e+02]
 [ 1.00000000e+00 -1.02020202e+

[[ 1.00000000e+00 -1.50000000e+01  2.25000000e+02 -3.37500000e+03]
 [ 1.00000000e+00 -1.47474747e+01  2.17488011e+02 -3.20739896e+03]
 [ 1.00000000e+00 -1.44949495e+01  2.10103561e+02 -3.04544050e+03]
 [ 1.00000000e+00 -1.42424242e+01  2.02846648e+02 -2.88902802e+03]
 [ 1.00000000e+00 -1.39898990e+01  1.95717274e+02 -2.73806489e+03]
 [ 1.00000000e+00 -1.37373737e+01  1.88715437e+02 -2.59245449e+03]
 [ 1.00000000e+00 -1.34848485e+01  1.81841139e+02 -2.45210020e+03]
 [ 1.00000000e+00 -1.32323232e+01  1.75094378e+02 -2.31690541e+03]
 [ 1.00000000e+00 -1.29797980e+01  1.68475156e+02 -2.18677348e+03]
 [ 1.00000000e+00 -1.27272727e+01  1.61983471e+02 -2.06160781e+03]
 [ 1.00000000e+00 -1.24747475e+01  1.55619325e+02 -1.94131178e+03]
 [ 1.00000000e+00 -1.22222222e+01  1.49382716e+02 -1.82578875e+03]
 [ 1.00000000e+00 -1.19696970e+01  1.43273646e+02 -1.71494212e+03]
 [ 1.00000000e+00 -1.17171717e+01  1.37292113e+02 -1.60867526e+03]
 [ 1.00000000e+00 -1.14646465e+01  1.31438119e+02 -1.50689156e

[[ 1.00000000e+00 -1.50000000e+01  2.25000000e+02 -3.37500000e+03
   5.06250000e+04]
 [ 1.00000000e+00 -1.47474747e+01  2.17488011e+02 -3.20739896e+03
   4.73010351e+04]
 [ 1.00000000e+00 -1.44949495e+01  2.10103561e+02 -3.04544050e+03
   4.41435063e+04]
 [ 1.00000000e+00 -1.42424242e+01  2.02846648e+02 -2.88902802e+03
   4.11467627e+04]
 [ 1.00000000e+00 -1.39898990e+01  1.95717274e+02 -2.73806489e+03
   3.83052512e+04]
 [ 1.00000000e+00 -1.37373737e+01  1.88715437e+02 -2.59245449e+03
   3.56135162e+04]
 [ 1.00000000e+00 -1.34848485e+01  1.81841139e+02 -2.45210020e+03
   3.30661997e+04]
 [ 1.00000000e+00 -1.32323232e+01  1.75094378e+02 -2.31690541e+03
   3.06580413e+04]
 [ 1.00000000e+00 -1.29797980e+01  1.68475156e+02 -2.18677348e+03
   2.83838781e+04]
 [ 1.00000000e+00 -1.27272727e+01  1.61983471e+02 -2.06160781e+03
   2.62386449e+04]
 [ 1.00000000e+00 -1.24747475e+01  1.55619325e+02 -1.94131178e+03
   2.42173742e+04]
 [ 1.00000000e+00 -1.22222222e+01  1.49382716e+02 -1.82578875e+03

[[ 1.00000000e+00 -1.50000000e+01  2.25000000e+02 -3.37500000e+03
   5.06250000e+04 -7.59375000e+05]
 [ 1.00000000e+00 -1.47474747e+01  2.17488011e+02 -3.20739896e+03
   4.73010351e+04 -6.97570821e+05]
 [ 1.00000000e+00 -1.44949495e+01  2.10103561e+02 -3.04544050e+03
   4.41435063e+04 -6.39857894e+05]
 [ 1.00000000e+00 -1.42424242e+01  2.02846648e+02 -2.88902802e+03
   4.11467627e+04 -5.86029651e+05]
 [ 1.00000000e+00 -1.39898990e+01  1.95717274e+02 -2.73806489e+03
   3.83052512e+04 -5.35886596e+05]
 [ 1.00000000e+00 -1.37373737e+01  1.88715437e+02 -2.59245449e+03
   3.56135162e+04 -4.89236183e+05]
 [ 1.00000000e+00 -1.34848485e+01  1.81841139e+02 -2.45210020e+03
   3.30661997e+04 -4.45892693e+05]
 [ 1.00000000e+00 -1.32323232e+01  1.75094378e+02 -2.31690541e+03
   3.06580413e+04 -4.05677112e+05]
 [ 1.00000000e+00 -1.29797980e+01  1.68475156e+02 -2.18677348e+03
   2.83838781e+04 -3.68417003e+05]
 [ 1.00000000e+00 -1.27272727e+01  1.61983471e+02 -2.06160781e+03
   2.62386449e+04 -3.3394

[[ 1.00000000e+00 -1.50000000e+01  2.25000000e+02 -3.37500000e+03
   5.06250000e+04 -7.59375000e+05  1.13906250e+07]
 [ 1.00000000e+00 -1.47474747e+01  2.17488011e+02 -3.20739896e+03
   4.73010351e+04 -6.97570821e+05  1.02874081e+07]
 [ 1.00000000e+00 -1.44949495e+01  2.10103561e+02 -3.04544050e+03
   4.41435063e+04 -6.39857894e+05  9.27470786e+06]
 [ 1.00000000e+00 -1.42424242e+01  2.02846648e+02 -2.88902802e+03
   4.11467627e+04 -5.86029651e+05  8.34648291e+06]
 [ 1.00000000e+00 -1.39898990e+01  1.95717274e+02 -2.73806489e+03
   3.83052512e+04 -5.35886596e+05  7.49699934e+06]
 [ 1.00000000e+00 -1.37373737e+01  1.88715437e+02 -2.59245449e+03
   3.56135162e+04 -4.89236183e+05  6.72082029e+06]
 [ 1.00000000e+00 -1.34848485e+01  1.81841139e+02 -2.45210020e+03
   3.30661997e+04 -4.45892693e+05  6.01279541e+06]
 [ 1.00000000e+00 -1.32323232e+01  1.75094378e+02 -2.31690541e+03
   3.06580413e+04 -4.05677112e+05  5.36805067e+06]
 [ 1.00000000e+00 -1.29797980e+01  1.68475156e+02 -2.18677348e+0

[[ 1.00000000e+00 -1.50000000e+01  2.25000000e+02 -3.37500000e+03
   5.06250000e+04 -7.59375000e+05  1.13906250e+07 -1.70859375e+08]
 [ 1.00000000e+00 -1.47474747e+01  2.17488011e+02 -3.20739896e+03
   4.73010351e+04 -6.97570821e+05  1.02874081e+07 -1.51713291e+08]
 [ 1.00000000e+00 -1.44949495e+01  2.10103561e+02 -3.04544050e+03
   4.41435063e+04 -6.39857894e+05  9.27470786e+06 -1.34436422e+08]
 [ 1.00000000e+00 -1.42424242e+01  2.02846648e+02 -2.88902802e+03
   4.11467627e+04 -5.86029651e+05  8.34648291e+06 -1.18874151e+08]
 [ 1.00000000e+00 -1.39898990e+01  1.95717274e+02 -2.73806489e+03
   3.83052512e+04 -5.35886596e+05  7.49699934e+06 -1.04882264e+08]
 [ 1.00000000e+00 -1.37373737e+01  1.88715437e+02 -2.59245449e+03
   3.56135162e+04 -4.89236183e+05  6.72082029e+06 -9.23264201e+07]
 [ 1.00000000e+00 -1.34848485e+01  1.81841139e+02 -2.45210020e+03
   3.30661997e+04 -4.45892693e+05  6.01279541e+06 -8.10816350e+07]
 [ 1.00000000e+00 -1.32323232e+01  1.75094378e+02 -2.31690541e+03
   

[[ 1.00000000e+00 -1.50000000e+01  2.25000000e+02 -3.37500000e+03
   5.06250000e+04 -7.59375000e+05  1.13906250e+07 -1.70859375e+08
   2.56289062e+09]
 [ 1.00000000e+00 -1.47474747e+01  2.17488011e+02 -3.20739896e+03
   4.73010351e+04 -6.97570821e+05  1.02874081e+07 -1.51713291e+08
   2.23738792e+09]
 [ 1.00000000e+00 -1.44949495e+01  2.10103561e+02 -3.04544050e+03
   4.41435063e+04 -6.39857894e+05  9.27470786e+06 -1.34436422e+08
   1.94864915e+09]
 [ 1.00000000e+00 -1.42424242e+01  2.02846648e+02 -2.88902802e+03
   4.11467627e+04 -5.86029651e+05  8.34648291e+06 -1.18874151e+08
   1.69305608e+09]
 [ 1.00000000e+00 -1.39898990e+01  1.95717274e+02 -2.73806489e+03
   3.83052512e+04 -5.35886596e+05  7.49699934e+06 -1.04882264e+08
   1.46729227e+09]
 [ 1.00000000e+00 -1.37373737e+01  1.88715437e+02 -2.59245449e+03
   3.56135162e+04 -4.89236183e+05  6.72082029e+06 -9.23264201e+07
   1.26832254e+09]
 [ 1.00000000e+00 -1.34848485e+01  1.81841139e+02 -2.45210020e+03
   3.30661997e+04 -4.4589269